name: Deploy to firebase
on:
  push:
    branches: ['master']
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      env:
        GITHUB_PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
    - name: Setup the code
      run: npm install
      env:
        GITHUB_PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
    - name: Deploy to Firebase
      uses: mohammed-atif/firebase-publish-react@v1.0
      env:
        GITHUB_PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      with:
        firebase-token: ${{ secrets.FIREBASE_TOKEN }}
      env:
        GITHUB_PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}